# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: it
pipeline: supervised_embeddings

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
